/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/localization.ts
var LOCALIZATION;
var init_localization = __esm({
  "src/localization.ts"() {
    LOCALIZATION = {
      es: {
        viewTitle: "Combat Ledger",
        openCommand: "Abrir Combat Ledger",
        round: "Ronda",
        nextTurn: "\u25B6 Siguiente turno",
        load: "\uFF0B Cargar",
        reset: "\u21BA Reset",
        resetConfirm: "\xBFReiniciar batalla? Se perder\xE1 el estado actual.",
        emptyState: "Sin combatientes. Pulsa \xABCargar\xBB para a\xF1adir notas.",
        init: "Init",
        ac: "CA",
        hp: "PV",
        shield: "Escudo",
        damageHeal: "\u2694 Da\xF1o / Curar",
        status: "\u25C8 Estado",
        note: "\u270E Nota",
        action: "\u26A1 Acci\xF3n",
        defeat: "Derrotar",
        revive: "Revivir",
        editInitiative: "Editar iniciativa",
        removeTitle: "Quitar del combate",
        dmgModalTitle: "Da\xF1o / Curaci\xF3n",
        dmgModalQty: "Cantidad",
        dmgModalHeal: "\u2665 Curar",
        dmgModalDmg: "\u2694 Da\xF1o",
        dmgModalUseShield: "Absorber da\xF1o con escudo",
        dmgModalNoShield: "Sin escudo disponible",
        condModalTitle: "Condiciones",
        condModalApply: "Aplicar",
        condModalDurationPlaceholder: "Duraci\xF3n en rondas",
        noteModalTitle: "Nota r\xE1pida",
        noteModalPlaceholder: "Anota algo sobre este combatiente...",
        noteModalSave: "Guardar",
        actionModalTitle: "Acci\xF3n",
        actionModalDamagePlaceholder: "Da\xF1o a aplicar",
        actionModalShieldLabel: "Permitir que el escudo absorba da\xF1o",
        actionModalNoCondition: "Sin condici\xF3n",
        actionModalNotePlaceholder: "Efecto o nota contextual",
        actionModalApply: "Aplicar acci\xF3n",
        pickModalTitle: "Selecciona combatientes",
        pickModalSearch: "Buscar nota...",
        pickModalLoad: "Cargar al combate",
        pickModalCancel: "Cancelar",
        pickModalSelectMin: "Selecciona al menos una nota.",
        // Settings
        settingsTitle: "Combat Ledger \u2014 Configuraci\xF3n",
        settingsLanguageName: "Idioma / Language",
        settingsLanguageDesc: "Selecciona el idioma de la interfaz (Select the interface language)",
        settingsFieldsTitle: "Campos de combatiente",
        settingsFieldsDesc: "Escribe el nombre exacto de la propiedad YAML que usas en tus notas.",
        settingsInitName: "Iniciativa",
        settingsInitDesc: "Propiedad para el valor de iniciativa",
        settingsHpName: "PV actuales",
        settingsHpDesc: "Propiedad para puntos de vida actuales (se usa tambi\xE9n como m\xE1ximo si no hay hp_max)",
        settingsHpMaxName: "PV m\xE1ximos",
        settingsHpMaxDesc: "Propiedad para puntos de vida m\xE1ximos",
        settingsShieldName: "Escudo",
        settingsShieldDesc: "Propiedad para el valor de escudo o puntos temporales. D\xE9jalo vac\xEDo si no usas escudo.",
        settingsAcName: "Clase de Armadura / Defensa",
        settingsAcDesc: "Propiedad para CA o defensa",
        settingsTypeName: "Tipo",
        settingsTypeDesc: 'Propiedad para el tipo: "PC", "Enemy" o "NPC"',
        settingsExtraName: "Campos extra",
        settingsExtraDesc: "Propiedades num\xE9ricas adicionales separadas por comas (ej. mp,stamina,stress)",
        settingsConditionsFieldName: "Campo de condiciones",
        settingsConditionsFieldDesc: "Propiedad YAML donde se sincronizan las condiciones activas.",
        settingsRealtimeTitle: "Sincronizaci\xF3n y da\xF1o",
        settingsRealtimeSyncName: "Sincronizaci\xF3n en tiempo real",
        settingsRealtimeSyncDesc: "Actualiza autom\xE1ticamente la nota original al cambiar PV, iniciativa, condiciones, escudo o extras.",
        settingsRealtimeModeName: "Sincronizar a",
        settingsRealtimeModeDesc: "Limita la sincronizaci\xF3n a personajes jugadores o apl\xEDcala a todos los combatientes.",
        settingsRealtimeModePc: "Solo PC",
        settingsRealtimeModeAll: "PC y NPC/Enemigos",
        settingsShieldAbsorbName: "El escudo absorbe da\xF1o",
        settingsShieldAbsorbDesc: "Cuando est\xE9 activo, el da\xF1o se resta primero del escudo antes de afectar los PV.",
        settingsCondTitle: "Condiciones / Estados",
        settingsCondColorDesc: "Personaliza el nombre y color de cada estado. El color se aplica al badge en la vista de combate.",
        settingsCondAddBtn: "\uFF0B A\xF1adir condici\xF3n",
        settingsCondDeleteBtn: "Eliminar",
        settingsCondNamePlaceholder: "Nombre del estado",
        settingsCondColorLabel: "Color",
        settingsFolderTitle: "Carpeta de combatientes (opcional)",
        settingsFolderFieldName: "Ruta de carpeta",
        settingsFolderFieldDesc: "Si indicas una carpeta (ej. Campa\xF1a/Criaturas), al pulsar \xABCargar\xBB cargar\xE1 todas las notas de esa carpeta autom\xE1ticamente. D\xE9jalo vac\xEDo para seleccionar manualmente.",
        // Logging Settings & UI
        logTitle: "Registro de Combate (Log)",
        logEnabledName: "Habilitar registro de combate",
        logEnabledDesc: "Registra el progreso del combate en una nota de Markdown.",
        logModeName: "Modo de registro",
        logModeDesc: "Elige si registrar en una nota nueva o en una existente.",
        logModeNew: "Nueva nota",
        logModeExisting: "Nota existente",
        logModeAsk: "Preguntar siempre",
        logHeaderName: "Encabezado del Registro",
        logHeaderDesc: "El encabezado Markdown (ej. ## Registro de Combate) debajo del cual se guardar\xE1 el log.",
        logFileNameName: "Nombre de archivo para nuevas notas",
        logFileNameDesc: "Nombre/Ruta del archivo para nuevas notas de log (puedes usar {date} para la fecha actual).",
        logSelectFile: "Selecciona la nota para el log",
        logHeaderPlaceholder: "## Registro de Combate",
        logStarted: "Combate iniciado.",
        logEnded: "Combate finalizado/reiniciado.",
        logActiveLogFile: "Archivo de registro activo",
        logSelectLogFileButton: "Configurar Registro",
        logConfigureTitle: "Configurar Registro de Combate",
        logChooseExistingFile: "Buscar nota existente...",
        logExistingFilePath: "Ruta de la nota existente",
        logCreateNewFile: "Crear nueva nota de registro",
        logSelectNoteNotice: "Por favor selecciona o crea una nota para el registro.",
        logNewNoteDefaultName: "Registro de Combate {date}",
        logModalHeading: "Nota de Registro",
        logHeadingDesc: "Selecciona d\xF3nde quieres registrar este combate:",
        logButtonNew: "Crear Nueva Nota",
        logButtonExisting: "Usar Nota Existente",
        logButtonNoLog: "No registrar"
      },
      en: {
        viewTitle: "Combat Ledger",
        openCommand: "Open Combat Ledger",
        round: "Round",
        nextTurn: "\u25B6 Next turn",
        load: "\uFF0B Load",
        reset: "\u21BA Reset",
        resetConfirm: "Reset battle? Current state will be lost.",
        emptyState: "No combatants. Click 'Load' to add notes.",
        init: "Init",
        ac: "AC",
        hp: "HP",
        shield: "Shield",
        damageHeal: "\u2694 Damage / Heal",
        status: "\u25C8 Status",
        note: "\u270E Note",
        action: "\u26A1 Action",
        defeat: "Defeat",
        revive: "Revive",
        editInitiative: "Edit initiative",
        removeTitle: "Remove from battle",
        dmgModalTitle: "Damage / Healing",
        dmgModalQty: "Amount",
        dmgModalHeal: "\u2665 Heal",
        dmgModalDmg: "\u2694 Damage",
        dmgModalUseShield: "Let shield absorb damage",
        dmgModalNoShield: "No shield available",
        condModalTitle: "Conditions",
        condModalApply: "Apply",
        condModalDurationPlaceholder: "Duration in rounds",
        noteModalTitle: "Quick note",
        noteModalPlaceholder: "Write something about this combatant...",
        noteModalSave: "Save",
        actionModalTitle: "Action",
        actionModalDamagePlaceholder: "Damage to apply",
        actionModalShieldLabel: "Allow shield to absorb damage",
        actionModalNoCondition: "No condition",
        actionModalNotePlaceholder: "Effect or contextual note",
        actionModalApply: "Apply action",
        pickModalTitle: "Select combatants",
        pickModalSearch: "Search note...",
        pickModalLoad: "Load to battle",
        pickModalCancel: "Cancel",
        pickModalSelectMin: "Select at least one note.",
        // Settings
        settingsTitle: "Combat Ledger \u2014 Settings",
        settingsLanguageName: "Idioma / Language",
        settingsLanguageDesc: "Selecciona el idioma de la interfaz (Select the interface language)",
        settingsFieldsTitle: "Combatant Fields",
        settingsFieldsDesc: "Write the exact name of the YAML property you use in your notes.",
        settingsInitName: "Initiative",
        settingsInitDesc: "Property for the initiative value",
        settingsHpName: "Current HP",
        settingsHpDesc: "Property for current hit points (also used as max if hp_max is missing)",
        settingsHpMaxName: "Max HP",
        settingsHpMaxDesc: "Property for maximum hit points",
        settingsShieldName: "Shield",
        settingsShieldDesc: "Property for shield or temporary hit points. Leave empty if unused.",
        settingsAcName: "Armor Class / Defense",
        settingsAcDesc: "Property for AC or defense",
        settingsTypeName: "Type",
        settingsTypeDesc: 'Property for type: "PC", "Enemy" or "NPC"',
        settingsExtraName: "Extra fields",
        settingsExtraDesc: "Additional numeric properties separated by commas (e.g. mp,stamina,stress)",
        settingsConditionsFieldName: "Conditions field",
        settingsConditionsFieldDesc: "YAML property where active conditions are synchronized.",
        settingsRealtimeTitle: "Sync and damage",
        settingsRealtimeSyncName: "Real-time sync",
        settingsRealtimeSyncDesc: "Automatically updates the original note when HP, initiative, conditions, shield, or extras change.",
        settingsRealtimeModeName: "Sync targets",
        settingsRealtimeModeDesc: "Limit synchronization to player characters or apply it to all combatants.",
        settingsRealtimeModePc: "PC only",
        settingsRealtimeModeAll: "PC and NPC/Enemies",
        settingsShieldAbsorbName: "Shield absorbs damage",
        settingsShieldAbsorbDesc: "When enabled, damage is removed from shield before it affects HP.",
        settingsCondTitle: "Conditions / States",
        settingsCondColorDesc: "Customize the name and color of each status. The color is applied to the badge in the combat view.",
        settingsCondAddBtn: "\uFF0B Add condition",
        settingsCondDeleteBtn: "Delete",
        settingsCondNamePlaceholder: "Status name",
        settingsCondColorLabel: "Color",
        settingsFolderTitle: "Combatant Folder (optional)",
        settingsFolderFieldName: "Folder path",
        settingsFolderFieldDesc: "If you specify a folder (e.g. Campaign/Creatures), clicking 'Load' will load all notes in that folder automatically. Leave empty to select manually.",
        // Logging Settings & UI
        logTitle: "Combat Log (Log)",
        logEnabledName: "Enable combat logging",
        logEnabledDesc: "Log combat progress into a Markdown note.",
        logModeName: "Logging mode",
        logModeDesc: "Choose whether to log in a new note or an existing one.",
        logModeNew: "New note",
        logModeExisting: "Existing note",
        logModeAsk: "Always ask",
        logHeaderName: "Log Header",
        logHeaderDesc: "The Markdown header (e.g. ## Combat Log) under which the log will be saved.",
        logFileNameName: "File name for new notes",
        logFileNameDesc: "File name/path for new log notes (you can use {date} for current date).",
        logSelectFile: "Select note for log",
        logHeaderPlaceholder: "## Combat Log",
        logStarted: "Combat started.",
        logEnded: "Combat ended/reset.",
        logActiveLogFile: "Active log file",
        logSelectLogFileButton: "Configure Log",
        logConfigureTitle: "Configure Combat Log",
        logChooseExistingFile: "Search existing note...",
        logExistingFilePath: "Existing note path",
        logCreateNewFile: "Create new log note",
        logSelectNoteNotice: "Please select or create a note for logging.",
        logNewNoteDefaultName: "Combat Log {date}",
        logModalHeading: "Log Note",
        logHeadingDesc: "Select where you want to log this combat:",
        logButtonNew: "Create New Note",
        logButtonExisting: "Use Existing Note",
        logButtonNoLog: "Do not log"
      }
    };
  }
});

// src/modals.ts
var modals_exports = {};
__export(modals_exports, {
  ActionModal: () => ActionModal,
  ConditionModal: () => ConditionModal,
  DmgModal: () => DmgModal,
  LogSetupModal: () => LogSetupModal,
  NoteModal: () => NoteModal,
  PickCombatantsModal: () => PickCombatantsModal
});
var import_obsidian, DmgModal, ConditionModal, NoteModal, ActionModal, PickCombatantsModal, LogSetupModal;
var init_modals = __esm({
  "src/modals.ts"() {
    import_obsidian = require("obsidian");
    init_localization();
    DmgModal = class extends import_obsidian.Modal {
      constructor(app, name, plugin, hasShield, onConfirm) {
        super(app);
        this.name = name;
        this.plugin = plugin;
        this.hasShield = hasShield;
        this.onConfirm = onConfirm;
      }
      onOpen() {
        const { contentEl } = this;
        const lang = this.plugin.settings.language;
        const t = LOCALIZATION[lang];
        contentEl.createEl("h3", { text: `${t.dmgModalTitle} \u2014 ${this.name}` });
        const wrap = contentEl.createDiv("bt-modal-content");
        const input = wrap.createEl("input", { type: "number", placeholder: t.dmgModalQty });
        input.min = "0";
        const shieldRow = wrap.createDiv("bt-modal-checkbox-row");
        const shieldToggle = shieldRow.createEl("input", { type: "checkbox" });
        shieldToggle.checked = this.plugin.settings.shieldAbsorbsDamage;
        shieldToggle.disabled = !this.hasShield;
        shieldRow.createEl("label", {
          text: this.hasShield ? t.dmgModalUseShield : t.dmgModalNoShield
        });
        const row = wrap.createDiv("bt-modal-actions");
        const healBtn = row.createEl("button", { cls: "bt-btn", text: t.dmgModalHeal });
        healBtn.onclick = () => {
          this.onConfirm(parseInt(input.value) || 0, true, false);
          this.close();
        };
        const dmgBtn = row.createEl("button", { cls: "bt-btn bt-btn-danger-soft", text: t.dmgModalDmg });
        dmgBtn.onclick = () => {
          this.onConfirm(parseInt(input.value) || 0, false, this.hasShield && shieldToggle.checked);
          this.close();
        };
        setTimeout(() => input.focus(), 50);
      }
      onClose() {
        this.contentEl.empty();
      }
    };
    ConditionModal = class extends import_obsidian.Modal {
      constructor(app, all, current, plugin, onConfirm) {
        super(app);
        this.allConditions = all;
        this.current = current.map((entry) => ({ ...entry }));
        this.plugin = plugin;
        this.onConfirm = onConfirm;
      }
      onOpen() {
        const { contentEl } = this;
        const lang = this.plugin.settings.language;
        const t = LOCALIZATION[lang];
        contentEl.createEl("h3", { text: t.condModalTitle });
        const grid = contentEl.createDiv("bt-cond-edit-grid");
        const selected = new Map(this.current.map((entry) => [entry.name, entry.duration]));
        this.allConditions.forEach((entry) => {
          const row2 = grid.createDiv("bt-cond-edit-row");
          const left = row2.createDiv("bt-cond-edit-main");
          const check = left.createEl("input", { type: "checkbox" });
          check.checked = selected.has(entry.name);
          const btn = left.createEl("button", {
            cls: `bt-cond-toggle${check.checked ? " selected" : ""}`,
            text: entry.name
          });
          const durationInput = row2.createEl("input", {
            cls: "bt-cond-duration-input",
            type: "number",
            placeholder: t.condModalDurationPlaceholder
          });
          durationInput.min = "1";
          const currentDuration = selected.get(entry.name);
          durationInput.value = currentDuration ? String(currentDuration) : "";
          durationInput.disabled = !check.checked;
          if (entry.color) {
            btn.style.color = check.checked ? "#fff" : entry.color;
            btn.style.borderColor = entry.color;
            btn.style.backgroundColor = check.checked ? entry.color : entry.color + "22";
          }
          const updateVisual = () => {
            btn.classList.toggle("selected", check.checked);
            durationInput.disabled = !check.checked;
            if (!check.checked)
              durationInput.value = "";
            if (entry.color) {
              btn.style.color = check.checked ? "#fff" : entry.color;
              btn.style.backgroundColor = check.checked ? entry.color : entry.color + "22";
            }
          };
          btn.onclick = () => {
            check.checked = !check.checked;
            updateVisual();
          };
          check.onchange = updateVisual;
        });
        const row = contentEl.createDiv("bt-modal-actions");
        const ok = row.createEl("button", { cls: "bt-btn bt-btn-primary", text: t.condModalApply });
        ok.onclick = () => {
          const updated = [];
          const rows = Array.from(grid.querySelectorAll(".bt-cond-edit-row"));
          rows.forEach((rowEl, idx) => {
            const check = rowEl.querySelector("input[type='checkbox']");
            const durationInput = rowEl.querySelector(".bt-cond-duration-input");
            const condition = this.allConditions[idx];
            if (!(check == null ? void 0 : check.checked) || !condition)
              return;
            const parsedDuration = Number(durationInput == null ? void 0 : durationInput.value);
            updated.push({
              name: condition.name,
              duration: Number.isFinite(parsedDuration) && parsedDuration > 0 ? parsedDuration : null
            });
          });
          this.onConfirm(updated);
          this.close();
        };
      }
      onClose() {
        this.contentEl.empty();
      }
    };
    NoteModal = class extends import_obsidian.Modal {
      constructor(app, current, plugin, onConfirm) {
        super(app);
        this.current = current;
        this.plugin = plugin;
        this.onConfirm = onConfirm;
      }
      onOpen() {
        const { contentEl } = this;
        const lang = this.plugin.settings.language;
        const t = LOCALIZATION[lang];
        contentEl.createEl("h3", { text: t.noteModalTitle });
        const wrap = contentEl.createDiv("bt-modal-content");
        const ta = wrap.createEl("textarea", { placeholder: t.noteModalPlaceholder });
        ta.value = this.current;
        const row = wrap.createDiv("bt-modal-actions");
        const ok = row.createEl("button", { cls: "bt-btn bt-btn-primary", text: t.noteModalSave });
        ok.onclick = () => {
          this.onConfirm(ta.value);
          this.close();
        };
        setTimeout(() => ta.focus(), 50);
      }
      onClose() {
        this.contentEl.empty();
      }
    };
    ActionModal = class extends import_obsidian.Modal {
      constructor(app, attacker, targets, conditions, plugin, onConfirm) {
        super(app);
        this.attacker = attacker;
        this.targets = targets;
        this.conditions = conditions;
        this.plugin = plugin;
        this.onConfirm = onConfirm;
      }
      onOpen() {
        const { contentEl } = this;
        const lang = this.plugin.settings.language;
        const t = LOCALIZATION[lang];
        contentEl.createEl("h3", { text: `${t.actionModalTitle} \u2014 ${this.attacker.name}` });
        const wrap = contentEl.createDiv("bt-modal-content");
        const targetSelect = wrap.createEl("select");
        this.targets.forEach((target) => {
          targetSelect.createEl("option", {
            value: target.id,
            text: `${target.name} (${t.hp} ${target.hp}/${target.hpMax})`
          });
        });
        const damageInput = wrap.createEl("input", {
          type: "number",
          placeholder: t.actionModalDamagePlaceholder
        });
        damageInput.min = "0";
        const shieldRow = wrap.createDiv("bt-modal-checkbox-row");
        const shieldToggle = shieldRow.createEl("input", { type: "checkbox" });
        shieldToggle.checked = this.plugin.settings.shieldAbsorbsDamage;
        shieldRow.createEl("label", { text: t.actionModalShieldLabel });
        const conditionSelect = wrap.createEl("select");
        conditionSelect.createEl("option", { value: "", text: t.actionModalNoCondition });
        this.conditions.forEach((entry) => {
          conditionSelect.createEl("option", { value: entry.name, text: entry.name });
        });
        const durationInput = wrap.createEl("input", {
          type: "number",
          placeholder: t.condModalDurationPlaceholder
        });
        durationInput.min = "1";
        const noteInput = wrap.createEl("textarea", {
          placeholder: t.actionModalNotePlaceholder
        });
        const row = wrap.createDiv("bt-modal-actions");
        const ok = row.createEl("button", { cls: "bt-btn bt-btn-primary", text: t.actionModalApply });
        ok.onclick = () => {
          const parsedDuration = Number(durationInput.value);
          this.onConfirm({
            targetId: targetSelect.value,
            damage: parseInt(damageInput.value) || 0,
            useShield: shieldToggle.checked,
            conditionName: conditionSelect.value,
            conditionDuration: Number.isFinite(parsedDuration) && parsedDuration > 0 ? parsedDuration : null,
            note: noteInput.value.trim()
          });
          this.close();
        };
        setTimeout(() => targetSelect.focus(), 50);
      }
      onClose() {
        this.contentEl.empty();
      }
    };
    PickCombatantsModal = class extends import_obsidian.Modal {
      constructor(app, plugin, onConfirm) {
        super(app);
        this.selected = /* @__PURE__ */ new Set();
        this.plugin = plugin;
        this.onConfirm = onConfirm;
      }
      onOpen() {
        const { contentEl } = this;
        const lang = this.plugin.settings.language;
        const t = LOCALIZATION[lang];
        contentEl.createEl("h3", { text: t.pickModalTitle });
        const searchInput = contentEl.createEl("input", {
          type: "text",
          placeholder: t.pickModalSearch,
          cls: "bt-modal-content"
        });
        searchInput.style.marginBottom = "8px";
        const list = contentEl.createDiv("bt-pick-list");
        const files = this.app.vault.getMarkdownFiles().sort((a, b) => a.basename.localeCompare(b.basename));
        const renderList = (filter) => {
          list.empty();
          files.filter((f) => !filter || f.basename.toLowerCase().includes(filter.toLowerCase())).forEach((file) => {
            const item = list.createDiv("bt-pick-item");
            const cb = item.createEl("input", { type: "checkbox" });
            cb.checked = this.selected.has(file.path);
            cb.onchange = () => {
              if (cb.checked)
                this.selected.add(file.path);
              else
                this.selected.delete(file.path);
            };
            const lbl = item.createEl("label", { text: file.basename });
            lbl.onclick = () => {
              cb.checked = !cb.checked;
              cb.dispatchEvent(new Event("change"));
            };
          });
        };
        renderList("");
        searchInput.oninput = () => renderList(searchInput.value);
        const row = contentEl.createDiv("bt-modal-actions");
        const cancel = row.createEl("button", { cls: "bt-btn", text: t.pickModalCancel });
        cancel.onclick = () => this.close();
        const ok = row.createEl("button", { cls: "bt-btn bt-btn-primary", text: t.pickModalLoad });
        ok.onclick = () => {
          const picked = files.filter((f) => this.selected.has(f.path));
          if (!picked.length) {
            new import_obsidian.Notice(t.pickModalSelectMin);
            return;
          }
          this.onConfirm(picked);
          this.close();
        };
        setTimeout(() => searchInput.focus(), 50);
      }
      onClose() {
        this.contentEl.empty();
      }
    };
    LogSetupModal = class extends import_obsidian.Modal {
      constructor(app, plugin, view, onChoose) {
        super(app);
        this.plugin = plugin;
        this.view = view;
        this.onChoose = onChoose;
      }
      onOpen() {
        const { contentEl } = this;
        const lang = this.plugin.settings.language;
        const t = LOCALIZATION[lang];
        contentEl.createEl("h3", { text: t.logConfigureTitle });
        contentEl.createEl("p", { text: t.logHeadingDesc, cls: "setting-item-description" });
        const container = contentEl.createDiv("bt-modal-content");
        const newFileBtn = container.createEl("button", { cls: "bt-btn bt-btn-primary", text: `\u{1F4DD} ${t.logCreateNewFile}` });
        newFileBtn.style.width = "100%";
        newFileBtn.style.padding = "8px";
        newFileBtn.style.marginBottom = "15px";
        newFileBtn.onclick = async () => {
          try {
            const file = await this.view.createNewLogFile();
            new import_obsidian.Notice(`${t.logActiveLogFile}: ${file.name}`);
            this.onChoose(file);
            this.close();
          } catch (e) {
            new import_obsidian.Notice(lang === "es" ? "Error al crear la nota de registro." : "Error creating log note.");
            console.error(e);
          }
        };
        const divider = container.createDiv();
        divider.style.textAlign = "center";
        divider.style.margin = "10px 0";
        divider.style.color = "var(--text-muted)";
        divider.style.fontSize = "11px";
        divider.setText("\u2500\u2500\u2500 " + (lang === "es" ? "O SELECCIONAR EXISTENTE" : "OR SELECT EXISTING") + " \u2500\u2500\u2500");
        const searchInput = container.createEl("input", {
          type: "text",
          placeholder: t.pickModalSearch
        });
        searchInput.style.marginBottom = "8px";
        const list = container.createDiv("bt-pick-list");
        list.style.maxHeight = "180px";
        const files = this.app.vault.getMarkdownFiles().sort((a, b) => a.basename.localeCompare(b.basename));
        const renderList = (filter) => {
          list.empty();
          files.filter((f) => !filter || f.basename.toLowerCase().includes(filter.toLowerCase())).slice(0, 50).forEach((file) => {
            const item = list.createDiv("bt-pick-item");
            item.style.padding = "6px 8px";
            item.setText(file.path);
            item.onclick = () => {
              new import_obsidian.Notice(`${t.logActiveLogFile}: ${file.name}`);
              this.onChoose(file);
              this.close();
            };
          });
        };
        renderList("");
        searchInput.oninput = () => renderList(searchInput.value);
        const row = contentEl.createDiv("bt-modal-actions");
        row.style.marginTop = "15px";
        const cancelBtn = row.createEl("button", { cls: "bt-btn", text: t.logButtonNoLog });
        cancelBtn.onclick = () => {
          this.onChoose(null);
          this.close();
        };
      }
      onClose() {
        this.contentEl.empty();
      }
    };
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BattleTrackerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian3 = require("obsidian");
init_localization();

// src/view.ts
var import_obsidian2 = require("obsidian");
init_localization();
init_modals();
var VIEW_TYPE = "combat-ledger-view";
var BattleTrackerView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.combatants = [];
    this.round = 1;
    this.activeCombatantId = null;
    this.editingInitiativeId = null;
    this.activeLogFile = null;
    this.logDismissed = false;
    this.logQueue = [];
    this.logSetupInProgress = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "Combat Ledger";
  }
  getIcon() {
    return "sword";
  }
  async onOpen() {
    this.render();
  }
  async writeToLog(actionText) {
    if (!this.plugin.settings.logEnabled)
      return;
    if (this.logDismissed)
      return;
    if (!this.activeLogFile) {
      this.logQueue.push(actionText);
      if (!this.logSetupInProgress) {
        this.triggerLogSetup();
      }
      return;
    }
    const lang = this.plugin.settings.language;
    const now = new Date();
    const timeStr = `${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}:${String(now.getSeconds()).padStart(2, "0")}`;
    const prefix = `[${timeStr}] (${lang === "es" ? "Ronda" : "Round"} ${this.round})`;
    const logLine = `- ${prefix} ${actionText}`;
    try {
      const file = this.activeLogFile;
      const content = await this.app.vault.read(file);
      const lines = content.split("\n");
      const targetHeader = this.plugin.settings.logHeader.trim();
      const headerRegex = /^(#+)\s+(.*)$/;
      const targetMatch = targetHeader.match(headerRegex);
      if (targetMatch) {
        const targetLevel = targetMatch[1].length;
        const targetName = targetMatch[2].trim().toLowerCase();
        let headerIndex = -1;
        for (let i = 0; i < lines.length; i++) {
          const match = lines[i].match(headerRegex);
          if (match && match[2].trim().toLowerCase() === targetName) {
            headerIndex = i;
            break;
          }
        }
        if (headerIndex !== -1) {
          let insertIndex = lines.length;
          for (let i = headerIndex + 1; i < lines.length; i++) {
            const match = lines[i].match(headerRegex);
            if (!match)
              continue;
            const level = match[1].length;
            if (level <= targetLevel) {
              insertIndex = i;
              break;
            }
          }
          lines.splice(insertIndex, 0, logLine);
          await this.app.vault.modify(file, lines.join("\n"));
          return;
        }
      }
      const newContent = content.trimEnd() + `

${targetHeader}
${logLine}
`;
      await this.app.vault.modify(file, newContent);
    } catch (e) {
      console.error("Error writing to combat log:", e);
      new import_obsidian2.Notice(lang === "es" ? "Error al escribir en el registro de combate." : "Error writing to combat log.");
    }
  }
  triggerLogSetup() {
    if (this.activeLogFile || this.logDismissed || this.logSetupInProgress)
      return;
    this.logSetupInProgress = true;
    const { LogSetupModal: LogSetupModal2 } = (init_modals(), __toCommonJS(modals_exports));
    new LogSetupModal2(this.app, this.plugin, this, async (file) => {
      this.logSetupInProgress = false;
      if (file) {
        this.activeLogFile = file;
        this.logDismissed = false;
        const lang = this.plugin.settings.language;
        const startMsg = LOCALIZATION[lang].logStarted;
        const currentQueue = [startMsg, ...this.logQueue];
        this.logQueue = [];
        for (const msg of currentQueue) {
          await this.writeToLog(msg);
        }
      } else {
        this.logDismissed = true;
        this.logQueue = [];
      }
      this.render();
    }).open();
  }
  async createNewLogFile() {
    const folderPath = this.plugin.settings.logFolder.trim();
    if (folderPath) {
      const folderExists = this.app.vault.getAbstractFileByPath(folderPath);
      if (!folderExists) {
        await this.app.vault.createFolder(folderPath);
      }
    }
    const now = new Date();
    const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")} ${String(now.getHours()).padStart(2, "0")}-${String(now.getMinutes()).padStart(2, "0")}`;
    let fileName = this.plugin.settings.logFileName.replace("{date}", dateStr);
    if (!fileName.endsWith(".md"))
      fileName += ".md";
    const fullPath = folderPath ? `${folderPath}/${fileName}` : fileName;
    let uniquePath = fullPath;
    let counter = 1;
    while (this.app.vault.getAbstractFileByPath(uniquePath)) {
      uniquePath = fullPath.replace(/\.md$/, ` (${counter}).md`);
      counter++;
    }
    const header = this.plugin.settings.logHeader;
    return await this.app.vault.create(uniquePath, `# ${fileName.replace(/\.md$/, "")}

${header}
`);
  }
  parseConditionToken(token) {
    if (typeof token === "string") {
      const match = token.match(/^(.*?)(?:\s*\((\d+)\))?$/);
      if (!match)
        return null;
      const name = match[1].trim();
      if (!name)
        return null;
      const duration = match[2] ? Number(match[2]) : null;
      return { name, duration: duration && duration > 0 ? duration : null };
    }
    if (token && typeof token === "object") {
      const maybe = token;
      if (typeof maybe.name !== "string" || !maybe.name.trim())
        return null;
      const durationValue = Number(maybe.duration);
      return {
        name: maybe.name.trim(),
        duration: Number.isFinite(durationValue) && durationValue > 0 ? durationValue : null
      };
    }
    return null;
  }
  parseStoredConditions(raw) {
    if (Array.isArray(raw)) {
      return raw.map((entry) => this.parseConditionToken(entry)).filter((entry) => Boolean(entry));
    }
    if (typeof raw === "string") {
      return raw.split(",").map((entry) => this.parseConditionToken(entry.trim())).filter((entry) => Boolean(entry));
    }
    const single = this.parseConditionToken(raw);
    return single ? [single] : [];
  }
  serializeConditions(conditions) {
    return conditions.map((entry) => entry.duration ? `${entry.name} (${entry.duration})` : entry.name);
  }
  formatConditionLabel(condition) {
    return condition.duration ? `${condition.name} \xB7 ${condition.duration}` : condition.name;
  }
  async fileToCombatant(file) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i;
    const f = this.plugin.settings.fields;
    const meta = (_b = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) != null ? _b : {};
    const extraNames = f.extra_fields.split(",").map((s) => s.trim()).filter(Boolean);
    const extraFields = {};
    for (const key of extraNames) {
      if (meta[key] !== void 0)
        extraFields[key] = Number(meta[key]) || 0;
    }
    const hpMax = Number((_d = (_c = meta[f.hp_max]) != null ? _c : meta[f.hp]) != null ? _d : 10) || 10;
    const hp = Number((_e = meta[f.hp]) != null ? _e : hpMax) || hpMax;
    const shield = f.shield ? Number((_f = meta[f.shield]) != null ? _f : 0) || 0 : 0;
    const storedConditions = f.conditions ? this.parseStoredConditions(meta[f.conditions]) : [];
    return {
      id: file.path,
      name: file.basename,
      initiative: Number((_g = meta[f.initiative]) != null ? _g : 0) || 0,
      hp,
      hpMax,
      shield,
      ac: Number((_h = meta[f.ac]) != null ? _h : 10) || 10,
      combatType: String((_i = meta[f.type]) != null ? _i : "NPC"),
      extraFields,
      conditions: storedConditions,
      notes: "",
      alive: hp > 0,
      file
    };
  }
  shouldSyncCombatant(combatant) {
    if (!this.plugin.settings.realtimeSync)
      return false;
    if (this.plugin.settings.realtimeSyncMode === "all")
      return true;
    return combatant.combatType === "PC";
  }
  async syncCombatantToNote(combatant) {
    if (!this.shouldSyncCombatant(combatant))
      return;
    const fields = this.plugin.settings.fields;
    try {
      await this.app.fileManager.processFrontMatter(combatant.file, (frontmatter) => {
        frontmatter[fields.hp] = combatant.hp;
        if (fields.initiative)
          frontmatter[fields.initiative] = combatant.initiative;
        if (fields.shield)
          frontmatter[fields.shield] = combatant.shield;
        if (fields.conditions)
          frontmatter[fields.conditions] = this.serializeConditions(combatant.conditions);
        Object.entries(combatant.extraFields).forEach(([key, value]) => {
          frontmatter[key] = value;
        });
      });
    } catch (error) {
      console.error("Failed to sync combatant note:", error);
      new import_obsidian2.Notice(this.plugin.settings.language === "es" ? `No se pudo sincronizar ${combatant.name}.` : `Could not sync ${combatant.name}.`);
    }
  }
  ensureActiveCombatant() {
    const alive = this.aliveSorted();
    if (!alive.length) {
      this.activeCombatantId = null;
      return;
    }
    if (!this.activeCombatantId || !alive.some((combatant) => combatant.id === this.activeCombatantId)) {
      this.activeCombatantId = alive[0].id;
    }
  }
  sorted() {
    return [...this.combatants].sort((a, b) => b.initiative - a.initiative || a.name.localeCompare(b.name));
  }
  aliveSorted() {
    return this.sorted().filter((combatant) => combatant.alive);
  }
  getCurrentTurnIndex(alive = this.aliveSorted()) {
    if (!alive.length || !this.activeCombatantId)
      return 0;
    const index = alive.findIndex((combatant) => combatant.id === this.activeCombatantId);
    return index >= 0 ? index : 0;
  }
  getCombatant(id) {
    return this.combatants.find((combatant) => combatant.id === id);
  }
  async processConditionDurations(combatant) {
    if (!combatant.conditions.length)
      return;
    const lang = this.plugin.settings.language;
    const retained = [];
    let changed = false;
    for (const condition of combatant.conditions) {
      if (condition.duration == null) {
        retained.push(condition);
        continue;
      }
      const nextDuration = condition.duration - 1;
      changed = true;
      if (nextDuration <= 0) {
        await this.writeToLog(lang === "es" ? `${combatant.name} pierde la condici\xF3n por expiraci\xF3n: ${condition.name}` : `${combatant.name} loses condition by expiration: ${condition.name}`);
        continue;
      }
      retained.push({ ...condition, duration: nextDuration });
    }
    if (changed) {
      combatant.conditions = retained;
      await this.syncCombatantToNote(combatant);
    }
  }
  async nextTurn() {
    const alive = this.aliveSorted();
    if (!alive.length)
      return;
    this.ensureActiveCombatant();
    const currentIndex = this.getCurrentTurnIndex(alive);
    const nextIndex = (currentIndex + 1) % alive.length;
    if (nextIndex === 0)
      this.round++;
    this.activeCombatantId = alive[nextIndex].id;
    const currentCombatant = alive[nextIndex];
    await this.processConditionDurations(currentCombatant);
    await this.writeToLog(this.plugin.settings.language === "es" ? `Turno de ${currentCombatant.name}` : `Turn of ${currentCombatant.name}`);
    this.render();
  }
  applyDamage(combatant, amount, heal, useShield) {
    if (heal) {
      const previous = combatant.hp;
      combatant.hp = Math.min(combatant.hpMax, combatant.hp + amount);
      if (combatant.hp > 0)
        combatant.alive = true;
      return {
        finalDamage: 0,
        absorbedByShield: 0,
        defeated: false,
        healed: combatant.hp - previous
      };
    }
    let remaining = Math.max(0, amount);
    let absorbedByShield = 0;
    if (useShield && combatant.shield > 0) {
      absorbedByShield = Math.min(combatant.shield, remaining);
      combatant.shield -= absorbedByShield;
      remaining -= absorbedByShield;
    }
    combatant.hp = Math.max(0, combatant.hp - remaining);
    if (combatant.hp === 0)
      combatant.alive = false;
    return {
      finalDamage: remaining,
      absorbedByShield,
      defeated: combatant.hp === 0,
      healed: 0
    };
  }
  async applyDmg(id, amount, heal, useShield) {
    const combatant = this.getCombatant(id);
    if (!combatant)
      return;
    const lang = this.plugin.settings.language;
    const result = this.applyDamage(combatant, amount, heal, useShield);
    if (heal) {
      await this.writeToLog(lang === "es" ? `${combatant.name} se cura ${result.healed} PV (PV: ${combatant.hp}/${combatant.hpMax})` : `${combatant.name} heals ${result.healed} HP (HP: ${combatant.hp}/${combatant.hpMax})`);
    } else {
      const shieldText = result.absorbedByShield > 0 ? lang === "es" ? `, ${result.absorbedByShield} absorbidos por escudo` : `, ${result.absorbedByShield} absorbed by shield` : "";
      await this.writeToLog(lang === "es" ? `${combatant.name} recibe ${result.finalDamage} de da\xF1o${shieldText} (PV: ${combatant.hp}/${combatant.hpMax})` : `${combatant.name} takes ${result.finalDamage} damage${shieldText} (HP: ${combatant.hp}/${combatant.hpMax})`);
      if (result.defeated) {
        await this.writeToLog(lang === "es" ? `${combatant.name} ha sido derrotado` : `${combatant.name} has been defeated`);
      }
    }
    await this.syncCombatantToNote(combatant);
    this.ensureActiveCombatant();
    this.render();
  }
  async setInitiative(id, initiative) {
    const combatant = this.getCombatant(id);
    if (!combatant)
      return;
    combatant.initiative = initiative;
    this.editingInitiativeId = null;
    await this.syncCombatantToNote(combatant);
    await this.writeToLog(this.plugin.settings.language === "es" ? `${combatant.name} cambia su iniciativa a ${initiative}` : `${combatant.name} changes initiative to ${initiative}`);
    this.ensureActiveCombatant();
    this.render();
  }
  async updateConditions(id, updated) {
    var _a, _b;
    const combatant = this.getCombatant(id);
    if (!combatant)
      return;
    const lang = this.plugin.settings.language;
    const oldMap = new Map(combatant.conditions.map((condition) => [condition.name, condition.duration]));
    const newMap = new Map(updated.map((condition) => [condition.name, condition.duration]));
    combatant.conditions = updated;
    for (const condition of updated) {
      if (!oldMap.has(condition.name)) {
        await this.writeToLog(lang === "es" ? `${combatant.name} obtiene la condici\xF3n: ${this.formatConditionLabel(condition)}` : `${combatant.name} gains condition: ${this.formatConditionLabel(condition)}`);
      } else if (oldMap.get(condition.name) !== condition.duration) {
        await this.writeToLog(lang === "es" ? `${combatant.name} actualiza la duraci\xF3n de ${condition.name} a ${(_a = condition.duration) != null ? _a : "\u221E"}` : `${combatant.name} updates ${condition.name} duration to ${(_b = condition.duration) != null ? _b : "\u221E"}`);
      }
    }
    for (const [name] of oldMap.entries()) {
      if (!newMap.has(name)) {
        await this.writeToLog(lang === "es" ? `${combatant.name} pierde la condici\xF3n: ${name}` : `${combatant.name} loses condition: ${name}`);
      }
    }
    await this.syncCombatantToNote(combatant);
    this.render();
  }
  async modExtra(id, key, delta) {
    var _a;
    const combatant = this.getCombatant(id);
    if (!combatant)
      return;
    combatant.extraFields[key] = Math.max(0, ((_a = combatant.extraFields[key]) != null ? _a : 0) + delta);
    await this.syncCombatantToNote(combatant);
    await this.writeToLog(this.plugin.settings.language === "es" ? `${combatant.name} - ${key.toUpperCase()} modificado a ${combatant.extraFields[key]}` : `${combatant.name} - ${key.toUpperCase()} modified to ${combatant.extraFields[key]}`);
    this.render();
  }
  async removeCombatant(id) {
    const combatant = this.getCombatant(id);
    if (combatant) {
      await this.writeToLog(this.plugin.settings.language === "es" ? `${combatant.name} retirado del combate` : `${combatant.name} removed from combat`);
    }
    this.combatants = this.combatants.filter((entry) => entry.id !== id);
    if (this.activeCombatantId === id)
      this.activeCombatantId = null;
    this.ensureActiveCombatant();
    this.render();
  }
  resetBattle() {
    void this.writeToLog(LOCALIZATION[this.plugin.settings.language].logEnded);
    this.combatants = [];
    this.round = 1;
    this.activeCombatantId = null;
    this.activeLogFile = null;
    this.logDismissed = false;
    this.logQueue = [];
    this.editingInitiativeId = null;
    this.render();
  }
  async applyAction(attackerId, payload) {
    const attacker = this.getCombatant(attackerId);
    const target = this.getCombatant(payload.targetId);
    if (!attacker || !target)
      return;
    const lang = this.plugin.settings.language;
    const result = payload.damage > 0 ? this.applyDamage(target, payload.damage, false, payload.useShield) : { finalDamage: 0, absorbedByShield: 0, defeated: false, healed: 0 };
    if (payload.conditionName) {
      const existing = target.conditions.find((condition) => condition.name === payload.conditionName);
      if (existing)
        existing.duration = payload.conditionDuration;
      else
        target.conditions.push({ name: payload.conditionName, duration: payload.conditionDuration });
    }
    const parts = [];
    if (payload.damage > 0) {
      parts.push(lang === "es" ? `le inflige ${result.finalDamage} de da\xF1o` : `deals ${result.finalDamage} damage`);
      if (result.absorbedByShield > 0) {
        parts.push(lang === "es" ? `${result.absorbedByShield} absorbidos por escudo` : `${result.absorbedByShield} absorbed by shield`);
      }
    }
    if (payload.conditionName) {
      parts.push(lang === "es" ? `aplica ${payload.conditionName}${payload.conditionDuration ? ` (${payload.conditionDuration})` : ""}` : `applies ${payload.conditionName}${payload.conditionDuration ? ` (${payload.conditionDuration})` : ""}`);
    }
    if (payload.note)
      parts.push(payload.note);
    const actionVerb = lang === "es" ? "ataca a" : "attacks";
    const suffix = parts.length ? ` ${lang === "es" ? "y" : "and"} ${parts.join(", ")}` : "";
    await this.writeToLog(lang === "es" ? `${attacker.name} ${actionVerb} ${target.name}${suffix}.` : `${attacker.name} ${actionVerb} ${target.name}${suffix}.`);
    if (result.defeated) {
      await this.writeToLog(lang === "es" ? `${target.name} ha sido derrotado` : `${target.name} has been defeated`);
    }
    await this.syncCombatantToNote(target);
    this.ensureActiveCombatant();
    this.render();
  }
  async loadFromVault() {
    const folder = this.plugin.settings.combatantFolder.trim();
    const lang = this.plugin.settings.language;
    let files;
    if (folder) {
      const folderObj = this.app.vault.getAbstractFileByPath(folder);
      if (!folderObj) {
        new import_obsidian2.Notice(lang === "es" ? `Carpeta "${folder}" no encontrada.` : `Folder "${folder}" not found.`);
        return;
      }
      files = this.app.vault.getMarkdownFiles().filter((file) => file.path.startsWith(folder + "/"));
    } else {
      new PickCombatantsModal(this.app, this.plugin, async (picked) => {
        const loaded2 = await Promise.all(picked.map((file) => this.fileToCombatant(file)));
        for (const combatant of loaded2) {
          if (!this.combatants.find((entry) => entry.id === combatant.id)) {
            this.combatants.push(combatant);
          }
        }
        this.ensureActiveCombatant();
        for (const combatant of loaded2) {
          await this.writeToLog(lang === "es" ? `Combatiente cargado: ${combatant.name} (Iniciativa: ${combatant.initiative}, PV: ${combatant.hp}/${combatant.hpMax})` : `Combatant loaded: ${combatant.name} (Initiative: ${combatant.initiative}, HP: ${combatant.hp}/${combatant.hpMax})`);
        }
        this.render();
        if (this.combatants.length > 0)
          this.triggerLogSetup();
      }).open();
      return;
    }
    const loaded = await Promise.all(files.map((file) => this.fileToCombatant(file)));
    for (const combatant of loaded) {
      if (!this.combatants.find((entry) => entry.id === combatant.id)) {
        this.combatants.push(combatant);
      }
    }
    this.ensureActiveCombatant();
    for (const combatant of loaded) {
      await this.writeToLog(lang === "es" ? `Combatiente cargado: ${combatant.name} (Iniciativa: ${combatant.initiative}, PV: ${combatant.hp}/${combatant.hpMax})` : `Combatant loaded: ${combatant.name} (Initiative: ${combatant.initiative}, HP: ${combatant.hp}/${combatant.hpMax})`);
    }
    this.render();
    if (this.combatants.length > 0)
      this.triggerLogSetup();
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("bt-panel");
    const lang = this.plugin.settings.language;
    const t = LOCALIZATION[lang];
    const conditionEntries = this.plugin.settings.conditions;
    const alive = this.aliveSorted();
    const allSorted = this.sorted();
    this.ensureActiveCombatant();
    const activeIndex = this.getCurrentTurnIndex(alive);
    const topBar = container.createDiv("bt-topbar");
    topBar.createDiv("bt-round-badge", (el) => el.setText(`${t.round} ${this.round}`));
    const topActions = topBar.createDiv("bt-top-actions");
    const nextBtn = topActions.createEl("button", { cls: "bt-btn bt-btn-primary" });
    nextBtn.innerHTML = t.nextTurn;
    nextBtn.onclick = () => void this.nextTurn();
    const loadBtn = topActions.createEl("button", { cls: "bt-btn" });
    loadBtn.innerHTML = t.load;
    loadBtn.onclick = () => void this.loadFromVault();
    if (this.plugin.settings.logEnabled) {
      const logBtn = topActions.createEl("button", {
        cls: `bt-btn${this.activeLogFile ? " bt-btn-primary" : ""}`,
        title: t.logSelectLogFileButton
      });
      logBtn.innerHTML = `\u{1F4DD} ${this.activeLogFile ? lang === "es" ? "Registrando" : "Logging" : lang === "es" ? "Registro" : "Log"}`;
      logBtn.onclick = () => this.triggerLogSetup();
    }
    const resetBtn = topActions.createEl("button", { cls: "bt-btn bt-btn-danger-soft" });
    resetBtn.innerHTML = t.reset;
    resetBtn.onclick = () => {
      if (confirm(t.resetConfirm))
        this.resetBattle();
    };
    if (alive.length) {
      const strip = container.createDiv("bt-init-strip");
      alive.forEach((combatant, index) => {
        const chip = strip.createDiv(`bt-init-chip${index === activeIndex ? " active" : ""}`);
        chip.setText(`${combatant.name} (${combatant.initiative})`);
      });
    }
    if (!this.combatants.length) {
      const empty = container.createDiv("bt-empty");
      empty.createEl("p", { text: t.emptyState });
      return;
    }
    allSorted.forEach((combatant) => {
      const isActive = combatant.alive && combatant.id === this.activeCombatantId;
      const ratio = combatant.hpMax > 0 ? combatant.hp / combatant.hpMax : 0;
      const card = container.createDiv(`bt-card${isActive ? " bt-card-active" : ""}${!combatant.alive ? " bt-card-dead" : ""}`);
      const header = card.createDiv("bt-card-header");
      const avatar = header.createDiv(`bt-avatar bt-avatar-${combatant.combatType === "PC" ? "pc" : combatant.combatType === "Enemy" ? "enemy" : "npc"}`);
      avatar.setText(combatant.name.slice(0, 2).toUpperCase());
      const nameWrap = header.createDiv("bt-name-wrap");
      const nameEl = nameWrap.createEl("span", { cls: "bt-name", text: combatant.name });
      nameEl.style.cursor = "pointer";
      nameEl.title = lang === "es" ? "Abrir nota" : "Open note";
      nameEl.onclick = () => void this.app.workspace.getLeaf(true).openFile(combatant.file);
      const metaRow = nameWrap.createDiv("bt-sub bt-init-edit-row");
      if (this.editingInitiativeId === combatant.id) {
        const initInput = metaRow.createEl("input", {
          cls: "bt-init-edit-input",
          type: "number"
        });
        initInput.value = String(combatant.initiative);
        const commit = () => void this.setInitiative(combatant.id, parseInt(initInput.value) || 0);
        initInput.onblur = commit;
        initInput.onkeydown = (evt) => {
          if (evt.key === "Enter")
            commit();
          if (evt.key === "Escape") {
            this.editingInitiativeId = null;
            this.render();
          }
        };
        setTimeout(() => {
          initInput.focus();
          initInput.select();
        }, 0);
      } else {
        const initText = metaRow.createEl("span", { text: `${t.init} ${combatant.initiative} \xB7 ${t.ac} ${combatant.ac}` });
        initText.ondblclick = () => {
          this.editingInitiativeId = combatant.id;
          this.render();
        };
        if (combatant.shield > 0) {
          metaRow.createEl("span", { cls: "bt-sub-shield", text: `${t.shield} ${combatant.shield}` });
        }
      }
      const badge = header.createDiv(`bt-badge bt-badge-${combatant.combatType === "PC" ? "pc" : combatant.combatType === "Enemy" ? "enemy" : "npc"}`);
      badge.setText(combatant.combatType);
      const initEditBtn = header.createEl("button", { cls: "bt-btn-icon", title: t.editInitiative });
      initEditBtn.setText("\u270E");
      initEditBtn.onclick = () => {
        this.editingInitiativeId = combatant.id;
        this.render();
      };
      const removeBtn = header.createEl("button", { cls: "bt-btn-icon", title: t.removeTitle });
      removeBtn.setText("\u2715");
      removeBtn.onclick = () => void this.removeCombatant(combatant.id);
      if (combatant.conditions.length) {
        const condRow = card.createDiv("bt-cond-row");
        combatant.conditions.forEach((condition) => {
          const tag = condRow.createDiv("bt-cond-tag");
          tag.setText(`${this.formatConditionLabel(condition)} \xD7`);
          const entry = conditionEntries.find((item) => item.name === condition.name);
          if (entry == null ? void 0 : entry.color) {
            tag.style.color = entry.color;
            tag.style.borderColor = entry.color;
            tag.style.backgroundColor = entry.color + "22";
          }
        });
      }
      const hpWrap = card.createDiv("bt-hp-wrap");
      const hpLabelRow = hpWrap.createDiv("bt-hp-label-row");
      hpLabelRow.createEl("span", { text: t.hp, cls: "bt-label" });
      hpLabelRow.createEl("span", { cls: "bt-hp-text", text: `${combatant.hp} / ${combatant.hpMax}` });
      const bar = hpWrap.createDiv("bt-bar");
      const fill = bar.createDiv("bt-bar-fill");
      fill.style.width = `${Math.max(0, ratio * 100)}%`;
      fill.className = `bt-bar-fill ${ratio > 0.6 ? "bt-hp-ok" : ratio > 0.3 ? "bt-hp-mid" : "bt-hp-low"}`;
      const extraNames = Object.keys(combatant.extraFields);
      if (extraNames.length) {
        const extraRow = card.createDiv("bt-extra-row");
        extraNames.forEach((key) => {
          const box = extraRow.createDiv("bt-extra-box");
          box.createEl("span", { cls: "bt-label", text: key.toUpperCase() });
          const valRow = box.createDiv("bt-extra-val-row");
          const minusBtn = valRow.createEl("button", { cls: "bt-btn-mini", text: "\u2212" });
          minusBtn.onclick = () => void this.modExtra(combatant.id, key, -1);
          valRow.createEl("span", { cls: "bt-extra-val", text: String(combatant.extraFields[key]) });
          const plusBtn = valRow.createEl("button", { cls: "bt-btn-mini", text: "+" });
          plusBtn.onclick = () => void this.modExtra(combatant.id, key, 1);
        });
      }
      if (combatant.notes) {
        card.createEl("p", { cls: "bt-notes", text: combatant.notes });
      }
      const actions = card.createDiv("bt-actions");
      const dmgBtn = actions.createEl("button", { cls: "bt-btn bt-btn-danger-soft" });
      dmgBtn.setText(t.damageHeal);
      dmgBtn.onclick = () => new DmgModal(this.app, combatant.name, this.plugin, combatant.shield > 0, (value, heal, useShield) => {
        void this.applyDmg(combatant.id, value, heal, useShield);
      }).open();
      const condBtn = actions.createEl("button", { cls: "bt-btn" });
      condBtn.setText(t.status);
      condBtn.onclick = () => new ConditionModal(this.app, conditionEntries, combatant.conditions, this.plugin, (updated) => {
        void this.updateConditions(combatant.id, updated);
      }).open();
      const noteBtn = actions.createEl("button", { cls: "bt-btn" });
      noteBtn.setText(t.note);
      noteBtn.onclick = () => new NoteModal(this.app, combatant.notes, this.plugin, (text) => {
        combatant.notes = text;
        void this.writeToLog(lang === "es" ? `${combatant.name} - Nota: ${text || "vaciada"}` : `${combatant.name} - Note: ${text || "cleared"}`);
        this.render();
      }).open();
      if (isActive && alive.length > 1) {
        const actionBtn = actions.createEl("button", { cls: "bt-btn bt-btn-primary" });
        actionBtn.setText(t.action);
        actionBtn.onclick = () => new ActionModal(
          this.app,
          combatant,
          alive.filter((entry) => entry.id !== combatant.id),
          conditionEntries,
          this.plugin,
          (payload) => void this.applyAction(combatant.id, payload)
        ).open();
      }
      if (combatant.alive) {
        const defeatBtn = actions.createEl("button", { cls: "bt-btn bt-btn-ghost" });
        defeatBtn.setText(t.defeat);
        defeatBtn.onclick = async () => {
          combatant.alive = false;
          combatant.hp = 0;
          await this.syncCombatantToNote(combatant);
          await this.writeToLog(lang === "es" ? `${combatant.name} ha sido derrotado` : `${combatant.name} has been defeated`);
          this.ensureActiveCombatant();
          this.render();
        };
      } else {
        const reviveBtn = actions.createEl("button", { cls: "bt-btn" });
        reviveBtn.setText(t.revive);
        reviveBtn.onclick = async () => {
          combatant.alive = true;
          combatant.hp = Math.max(1, combatant.hp);
          await this.syncCombatantToNote(combatant);
          await this.writeToLog(lang === "es" ? `${combatant.name} ha resucitado` : `${combatant.name} has been revived`);
          this.ensureActiveCombatant();
          this.render();
        };
      }
    });
  }
  async onClose() {
    await Promise.resolve();
  }
};

// src/settings.ts
var DEFAULT_CONDITIONS_ES = [
  { name: "Aturdido", color: "#f59e0b" },
  { name: "Envenenado", color: "#22c55e" },
  { name: "Paralizado", color: "#a855f7" },
  { name: "Asustado", color: "#f97316" },
  { name: "Invisible", color: "#94a3b8" },
  { name: "Concentraci\xF3n", color: "#3b82f6" },
  { name: "Maldito", color: "#9333ea" },
  { name: "Quemando", color: "#ef4444" },
  { name: "Ca\xEDdo", color: "#78716c" },
  { name: "Cegado", color: "#1e293b" }
];
var DEFAULT_CONDITIONS_EN = [
  { name: "Stunned", color: "#f59e0b" },
  { name: "Poisoned", color: "#22c55e" },
  { name: "Paralyzed", color: "#a855f7" },
  { name: "Frightened", color: "#f97316" },
  { name: "Invisible", color: "#94a3b8" },
  { name: "Concentration", color: "#3b82f6" },
  { name: "Cursed", color: "#9333ea" },
  { name: "Burning", color: "#ef4444" },
  { name: "Prone", color: "#78716c" },
  { name: "Blinded", color: "#1e293b" }
];
var DEFAULT_SETTINGS = {
  language: "es",
  fields: {
    initiative: "initiative",
    hp: "hp",
    hp_max: "hp_max",
    shield: "shield",
    ac: "ac",
    type: "type",
    extra_fields: "mp,stamina",
    conditions: "conditions"
  },
  conditions: DEFAULT_CONDITIONS_ES,
  combatantFolder: "",
  realtimeSync: false,
  realtimeSyncMode: "pc",
  shieldAbsorbsDamage: true,
  logEnabled: true,
  logMode: "ask",
  logHeader: "## Registro de Combate",
  logFileName: "Registro de Combate {date}",
  logFolder: ""
};
var BattleTrackerSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const lang = this.plugin.settings.language;
    const t = LOCALIZATION[lang];
    containerEl.createEl("h2", { text: t.settingsTitle });
    new import_obsidian3.Setting(containerEl).setName(t.settingsLanguageName).setDesc(t.settingsLanguageDesc).addDropdown(
      (dropdown) => dropdown.addOption("es", "Espa\xF1ol").addOption("en", "English").setValue(this.plugin.settings.language).onChange(async (value) => {
        const oldLang = this.plugin.settings.language;
        if (oldLang === value)
          return;
        const currentNames = this.plugin.settings.conditions.map((c) => c.name).join(",");
        const esNames = DEFAULT_CONDITIONS_ES.map((c) => c.name).join(",");
        const enNames = DEFAULT_CONDITIONS_EN.map((c) => c.name).join(",");
        if (currentNames === esNames || currentNames === enNames) {
          this.plugin.settings.conditions = value === "es" ? [...DEFAULT_CONDITIONS_ES] : [...DEFAULT_CONDITIONS_EN];
        }
        const esHeader = "## Registro de Combate";
        const enHeader = "## Combat Log";
        if (this.plugin.settings.logHeader === esHeader || this.plugin.settings.logHeader === enHeader) {
          this.plugin.settings.logHeader = value === "es" ? esHeader : enHeader;
        }
        const esFile = "Registro de Combate {date}";
        const enFile = "Combat Log {date}";
        if (this.plugin.settings.logFileName === esFile || this.plugin.settings.logFileName === enFile) {
          this.plugin.settings.logFileName = value === "es" ? esFile : enFile;
        }
        this.plugin.settings.language = value;
        await this.plugin.saveSettings();
        this.display();
        const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE);
        leaves.forEach((leaf) => {
          if (leaf.view instanceof BattleTrackerView) {
            leaf.view.render();
          }
        });
      })
    );
    containerEl.createEl("h3", { text: t.settingsFieldsTitle });
    containerEl.createEl("p", { text: t.settingsFieldsDesc, cls: "setting-item-description" });
    const f = this.plugin.settings.fields;
    new import_obsidian3.Setting(containerEl).setName(t.settingsInitName).setDesc(t.settingsInitDesc).addText((text) => text.setValue(f.initiative).onChange(async (v) => {
      f.initiative = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName(t.settingsHpName).setDesc(t.settingsHpDesc).addText((text) => text.setValue(f.hp).onChange(async (v) => {
      f.hp = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName(t.settingsHpMaxName).setDesc(t.settingsHpMaxDesc).addText((text) => text.setValue(f.hp_max).onChange(async (v) => {
      f.hp_max = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName(t.settingsShieldName).setDesc(t.settingsShieldDesc).addText((text) => text.setValue(f.shield).onChange(async (v) => {
      f.shield = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName(t.settingsAcName).setDesc(t.settingsAcDesc).addText((text) => text.setValue(f.ac).onChange(async (v) => {
      f.ac = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName(t.settingsTypeName).setDesc(t.settingsTypeDesc).addText((text) => text.setValue(f.type).onChange(async (v) => {
      f.type = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName(t.settingsExtraName).setDesc(t.settingsExtraDesc).addText((text) => text.setValue(f.extra_fields).onChange(async (v) => {
      f.extra_fields = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName(t.settingsConditionsFieldName).setDesc(t.settingsConditionsFieldDesc).addText((text) => text.setValue(f.conditions).onChange(async (v) => {
      f.conditions = v;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: t.settingsRealtimeTitle });
    new import_obsidian3.Setting(containerEl).setName(t.settingsRealtimeSyncName).setDesc(t.settingsRealtimeSyncDesc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.realtimeSync).onChange(async (v) => {
        this.plugin.settings.realtimeSync = v;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.realtimeSync) {
      new import_obsidian3.Setting(containerEl).setName(t.settingsRealtimeModeName).setDesc(t.settingsRealtimeModeDesc).addDropdown(
        (dropdown) => dropdown.addOption("pc", t.settingsRealtimeModePc).addOption("all", t.settingsRealtimeModeAll).setValue(this.plugin.settings.realtimeSyncMode).onChange(async (value) => {
          this.plugin.settings.realtimeSyncMode = value;
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian3.Setting(containerEl).setName(t.settingsShieldAbsorbName).setDesc(t.settingsShieldAbsorbDesc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.shieldAbsorbsDamage).onChange(async (v) => {
        this.plugin.settings.shieldAbsorbsDamage = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: t.settingsCondTitle });
    containerEl.createEl("p", { text: t.settingsCondColorDesc, cls: "setting-item-description" });
    const condListEl = containerEl.createDiv("bt-settings-cond-list");
    this.renderConditionRows(condListEl, t);
    containerEl.createEl("h3", { text: t.settingsFolderTitle });
    new import_obsidian3.Setting(containerEl).setName(t.settingsFolderFieldName).setDesc(t.settingsFolderFieldDesc).addText(
      (text) => text.setPlaceholder("Campa\xF1a/Criaturas").setValue(this.plugin.settings.combatantFolder).onChange(async (v) => {
        this.plugin.settings.combatantFolder = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: t.logTitle });
    new import_obsidian3.Setting(containerEl).setName(t.logEnabledName).setDesc(t.logEnabledDesc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.logEnabled).onChange(async (v) => {
        this.plugin.settings.logEnabled = v;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.logEnabled) {
      new import_obsidian3.Setting(containerEl).setName(t.logHeaderName).setDesc(t.logHeaderDesc).addText(
        (text) => text.setPlaceholder(t.logHeaderPlaceholder).setValue(this.plugin.settings.logHeader).onChange(async (v) => {
          this.plugin.settings.logHeader = v;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian3.Setting(containerEl).setName(t.logFileNameName).setDesc(t.logFileNameDesc).addText(
        (text) => text.setValue(this.plugin.settings.logFileName).onChange(async (v) => {
          this.plugin.settings.logFileName = v;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian3.Setting(containerEl).setName(lang === "es" ? "Carpeta de notas de registro" : "Folder for log notes").setDesc(lang === "es" ? "Ruta de la carpeta donde se crear\xE1n las nuevas notas de registro (ej. Logs). D\xE9jalo vac\xEDo para el directorio ra\xEDz." : "Path of the folder where new log notes will be created (e.g. Logs). Leave empty for root.").addText(
        (text) => text.setPlaceholder("Logs").setValue(this.plugin.settings.logFolder).onChange(async (v) => {
          this.plugin.settings.logFolder = v;
          await this.plugin.saveSettings();
        })
      );
    }
  }
  // ── Render condition rows ──────────────────────────────────────────────────
  renderConditionRows(condListEl, t) {
    condListEl.empty();
    const conditions = this.plugin.settings.conditions;
    conditions.forEach((entry, idx) => {
      const row = condListEl.createDiv("bt-settings-cond-row");
      const preview = row.createDiv("bt-settings-cond-preview");
      this.applyCondPreviewStyle(preview, entry.color);
      preview.setText(entry.name.slice(0, 2).toUpperCase() || "??");
      const nameInput = row.createEl("input", {
        cls: "bt-settings-cond-name",
        type: "text"
      });
      nameInput.value = entry.name;
      nameInput.placeholder = t.settingsCondNamePlaceholder;
      nameInput.addEventListener("change", async () => {
        conditions[idx].name = nameInput.value.trim();
        preview.setText(conditions[idx].name.slice(0, 2).toUpperCase() || "??");
        await this.plugin.saveSettings();
        this.refreshView();
      });
      row.createEl("span", { cls: "bt-settings-color-label", text: t.settingsCondColorLabel });
      const colorInput = row.createEl("input", {
        cls: "bt-settings-color-input",
        type: "color"
      });
      colorInput.value = entry.color || "#888888";
      colorInput.addEventListener("input", async () => {
        conditions[idx].color = colorInput.value;
        this.applyCondPreviewStyle(preview, colorInput.value);
        await this.plugin.saveSettings();
        this.refreshView();
      });
      const delBtn = row.createEl("button", {
        cls: "bt-settings-cond-del",
        text: t.settingsCondDeleteBtn
      });
      delBtn.onclick = async () => {
        conditions.splice(idx, 1);
        await this.plugin.saveSettings();
        this.renderConditionRows(condListEl, t);
        this.refreshView();
      };
    });
    const addBtn = condListEl.createEl("button", {
      cls: "bt-settings-cond-add",
      text: t.settingsCondAddBtn
    });
    addBtn.onclick = async () => {
      conditions.push({ name: "", color: "#888888" });
      await this.plugin.saveSettings();
      this.renderConditionRows(condListEl, t);
      const rows = condListEl.querySelectorAll(".bt-settings-cond-name");
      if (rows.length)
        rows[rows.length - 1].focus();
    };
  }
  applyCondPreviewStyle(el, color) {
    const c = color || "var(--text-accent)";
    el.style.color = c;
    el.style.borderColor = c;
    el.style.backgroundColor = color ? color + "22" : "transparent";
  }
  refreshView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    leaves.forEach((leaf) => {
      if (leaf.view instanceof BattleTrackerView) {
        leaf.view.render();
      }
    });
  }
};

// src/main.ts
var BattleTrackerPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    const registry = this.app.viewRegistry;
    if (registry && registry.viewByType && registry.viewByType[VIEW_TYPE]) {
      delete registry.viewByType[VIEW_TYPE];
    }
    this.registerView(VIEW_TYPE, (leaf) => new BattleTrackerView(leaf, this));
    this.addRibbonIcon("sword", "Combat Ledger", () => this.activateView());
    this.addCommand({
      id: "open-combat-ledger",
      name: this.settings.language === "es" ? "Abrir Combat Ledger" : "Open Combat Ledger",
      callback: () => this.activateView()
    });
    this.addSettingTab(new BattleTrackerSettingTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const existing = workspace.getLeavesOfType(VIEW_TYPE);
    if (existing.length) {
      leaf = existing[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (!leaf)
        return;
      await leaf.setViewState({ type: VIEW_TYPE, active: true });
    }
    if (leaf)
      workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    var _a;
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.settings.fields = Object.assign({}, DEFAULT_SETTINGS.fields, (_a = this.settings.fields) != null ? _a : {});
    if (typeof this.settings.conditions === "string") {
      this.settings.conditions = this.settings.conditions.split(",").map((s) => s.trim()).filter(Boolean).map((name) => ({ name, color: "" }));
      await this.saveSettings();
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
