export const LOCALIZATION = {
	es: {
		viewTitle: "Combat Ledger",
		openCommand: "Abrir Combat Ledger",
		round: "Ronda",
		nextTurn: "▶ Siguiente turno",
		load: "＋ Cargar",
		reset: "↺ Reset",
		resetConfirm: "¿Reiniciar batalla? Se perderá el estado actual.",
		emptyState: "Sin combatientes. Pulsa «Cargar» para añadir notas.",
		init: "Init",
		ac: "CA",
		hp: "PV",
		damageHeal: "⚔ Daño / Curar",
		status: "◈ Estado",
		note: "✎ Nota",
		defeat: "Derrotar",
		revive: "Revivir",
		removeTitle: "Quitar del combate",
		dmgModalTitle: "Daño / Curación",
		dmgModalQty: "Cantidad",
		dmgModalHeal: "♥ Curar",
		dmgModalDmg: "⚔ Daño",
		condModalTitle: "Condiciones",
		condModalApply: "Aplicar",
		noteModalTitle: "Nota rápida",
		noteModalPlaceholder: "Anota algo sobre este combatiente...",
		noteModalSave: "Guardar",
		pickModalTitle: "Selecciona combatientes",
		pickModalSearch: "Buscar nota...",
		pickModalLoad: "Cargar al combate",
		pickModalCancel: "Cancelar",
		pickModalSelectMin: "Selecciona al menos una nota.",
		
		// Settings
		settingsTitle: "Combat Ledger — Configuración",
		settingsLanguageName: "Idioma / Language",
		settingsLanguageDesc: "Selecciona el idioma de la interfaz (Select the interface language)",
		settingsFieldsTitle: "Campos de combatiente",
		settingsFieldsDesc: "Escribe el nombre exacto de la propiedad YAML que usas en tus notas.",
		settingsInitName: "Iniciativa",
		settingsInitDesc: "Propiedad para el valor de iniciativa",
		settingsHpName: "PV actuales",
		settingsHpDesc: "Propiedad para puntos de vida actuales (se usa también como máximo si no hay hp_max)",
		settingsHpMaxName: "PV máximos",
		settingsHpMaxDesc: "Propiedad para puntos de vida máximos",
		settingsAcName: "Clase de Armadura / Defensa",
		settingsAcDesc: "Propiedad para CA o defensa",
		settingsTypeName: "Tipo",
		settingsTypeDesc: "Propiedad para el tipo: \"PC\", \"Enemy\" o \"NPC\"",
		settingsExtraName: "Campos extra",
		settingsExtraDesc: "Propiedades numéricas adicionales separadas por comas (ej. mp,stamina,stress)",
		settingsCondTitle: "Condiciones / Estados",
		settingsCondColorDesc: "Personaliza el nombre y color de cada estado. El color se aplica al badge en la vista de combate.",
		settingsCondAddBtn: "＋ Añadir condición",
		settingsCondDeleteBtn: "Eliminar",
		settingsCondNamePlaceholder: "Nombre del estado",
		settingsCondColorLabel: "Color",
		settingsFolderTitle: "Carpeta de combatientes (opcional)",
		settingsFolderFieldName: "Ruta de carpeta",
		settingsFolderFieldDesc: "Si indicas una carpeta (ej. Campaña/Criaturas), al pulsar «Cargar» cargará todas las notas de esa carpeta automáticamente. Déjalo vacío para seleccionar manualmente.",
		
		// Logging Settings & UI
		logTitle: "Registro de Combate (Log)",
		logEnabledName: "Habilitar registro de combate",
		logEnabledDesc: "Registra el progreso del combate en una nota de Markdown.",
		logModeName: "Modo de registro",
		logModeDesc: "Elige si registrar en una nota nueva o en una existente.",
		logModeNew: "Nueva nota",
		logModeExisting: "Nota existente",
		logModeAsk: "Preguntar siempre",
		logHeaderName: "Encabezado del Registro",
		logHeaderDesc: "El encabezado Markdown (ej. ## Registro de Combate) debajo del cual se guardará el log.",
		logFileNameName: "Nombre de archivo para nuevas notas",
		logFileNameDesc: "Nombre/Ruta del archivo para nuevas notas de log (puedes usar {date} para la fecha actual).",
		logSelectFile: "Selecciona la nota para el log",
		logHeaderPlaceholder: "## Registro de Combate",
		logStarted: "Combate iniciado.",
		logEnded: "Combate finalizado/reiniciado.",
		logActiveLogFile: "Archivo de registro activo",
		logSelectLogFileButton: "Configurar Registro",
		logConfigureTitle: "Configurar Registro de Combate",
		logChooseExistingFile: "Buscar nota existente...",
		logExistingFilePath: "Ruta de la nota existente",
		logCreateNewFile: "Crear nueva nota de registro",
		logSelectNoteNotice: "Por favor selecciona o crea una nota para el registro.",
		logNewNoteDefaultName: "Registro de Combate {date}",
		logModalHeading: "Nota de Registro",
		logHeadingDesc: "Selecciona dónde quieres registrar este combate:",
		logButtonNew: "Crear Nueva Nota",
		logButtonExisting: "Usar Nota Existente",
		logButtonNoLog: "No registrar",
	},
	en: {
		viewTitle: "Combat Ledger",
		openCommand: "Open Combat Ledger",
		round: "Round",
		nextTurn: "▶ Next turn",
		load: "＋ Load",
		reset: "↺ Reset",
		resetConfirm: "Reset battle? Current state will be lost.",
		emptyState: "No combatants. Click 'Load' to add notes.",
		init: "Init",
		ac: "AC",
		hp: "HP",
		damageHeal: "⚔ Damage / Heal",
		status: "◈ Status",
		note: "✎ Note",
		defeat: "Defeat",
		revive: "Revive",
		removeTitle: "Remove from battle",
		dmgModalTitle: "Damage / Healing",
		dmgModalQty: "Amount",
		dmgModalHeal: "♥ Heal",
		dmgModalDmg: "⚔ Damage",
		condModalTitle: "Conditions",
		condModalApply: "Apply",
		noteModalTitle: "Quick note",
		noteModalPlaceholder: "Write something about this combatant...",
		noteModalSave: "Save",
		pickModalTitle: "Select combatants",
		pickModalSearch: "Search note...",
		pickModalLoad: "Load to battle",
		pickModalCancel: "Cancel",
		pickModalSelectMin: "Select at least one note.",
		
		// Settings
		settingsTitle: "Combat Ledger — Settings",
		settingsLanguageName: "Idioma / Language",
		settingsLanguageDesc: "Selecciona el idioma de la interfaz (Select the interface language)",
		settingsFieldsTitle: "Combatant Fields",
		settingsFieldsDesc: "Write the exact name of the YAML property you use in your notes.",
		settingsInitName: "Initiative",
		settingsInitDesc: "Property for the initiative value",
		settingsHpName: "Current HP",
		settingsHpDesc: "Property for current hit points (also used as max if hp_max is missing)",
		settingsHpMaxName: "Max HP",
		settingsHpMaxDesc: "Property for maximum hit points",
		settingsAcName: "Armor Class / Defense",
		settingsAcDesc: "Property for AC or defense",
		settingsTypeName: "Type",
		settingsTypeDesc: "Property for type: \"PC\", \"Enemy\" or \"NPC\"",
		settingsExtraName: "Extra fields",
		settingsExtraDesc: "Additional numeric properties separated by commas (e.g. mp,stamina,stress)",
		settingsCondTitle: "Conditions / States",
		settingsCondColorDesc: "Customize the name and color of each status. The color is applied to the badge in the combat view.",
		settingsCondAddBtn: "＋ Add condition",
		settingsCondDeleteBtn: "Delete",
		settingsCondNamePlaceholder: "Status name",
		settingsCondColorLabel: "Color",
		settingsFolderTitle: "Combatant Folder (optional)",
		settingsFolderFieldName: "Folder path",
		settingsFolderFieldDesc: "If you specify a folder (e.g. Campaign/Creatures), clicking 'Load' will load all notes in that folder automatically. Leave empty to select manually.",
		
		// Logging Settings & UI
		logTitle: "Combat Log (Log)",
		logEnabledName: "Enable combat logging",
		logEnabledDesc: "Log combat progress into a Markdown note.",
		logModeName: "Logging mode",
		logModeDesc: "Choose whether to log in a new note or an existing one.",
		logModeNew: "New note",
		logModeExisting: "Existing note",
		logModeAsk: "Always ask",
		logHeaderName: "Log Header",
		logHeaderDesc: "The Markdown header (e.g. ## Combat Log) under which the log will be saved.",
		logFileNameName: "File name for new notes",
		logFileNameDesc: "File name/path for new log notes (you can use {date} for current date).",
		logSelectFile: "Select note for log",
		logHeaderPlaceholder: "## Combat Log",
		logStarted: "Combat started.",
		logEnded: "Combat ended/reset.",
		logActiveLogFile: "Active log file",
		logSelectLogFileButton: "Configure Log",
		logConfigureTitle: "Configure Combat Log",
		logChooseExistingFile: "Search existing note...",
		logExistingFilePath: "Existing note path",
		logCreateNewFile: "Create new log note",
		logSelectNoteNotice: "Please select or create a note for logging.",
		logNewNoteDefaultName: "Combat Log {date}",
		logModalHeading: "Log Note",
		logHeadingDesc: "Select where you want to log this combat:",
		logButtonNew: "Create New Note",
		logButtonExisting: "Use Existing Note",
		logButtonNoLog: "Do not log",
	}
};
